"""Finding diagonal transversal gates on translation-invariant CSS codes.

The main entry point is the TIGateFinder class. The underlying structures mirror
the ones in core, adapted to translation invariance:

- TIPhaseLocs: supports of translation classes of phase functions. Each generator
  represents a phase function applied at every lattice translate of its support.
  Supports are stored in normalized form (see normalize_ti_loc).
- TIZ2Hom: a translation-invariant Z2-linear map in sparse column form. Column j
  lists the images of the source generator (0, j); images of translated generators
  follow by translation invariance.
- TITwoGroupHom: a homomorphism whose target 2-group is generated by lattice
  translates of internal generators. The coefficients are stored densely in a
  lin.Hom (attribute h), while the attribute ti_support records which translate
  each target generator of h refers to; this keeps the data finite even though
  the group of all translates is infinite.

Generators of infinite modules/2-groups are specified by pairs of a coordinate
tuple (the lattice translate) and an internal generator number within the unit
cell; in QEC terms these pairs are qubit or check specifiers.
"""
from __future__ import annotations

from itertools import combinations, product
from typing import Iterable, Optional, Sequence, Union

import numpy as np
import twogroup_linalg as lin

from . import flint_wrappers as fl
from .core import (GateFinder, GateFinderResults, PhaseLocs, TwoGroupElem,
                   TwoGroupHom, Z2Hom, _check_phase_locs_dims, assemble_pullback,
                   pullback_column)

Coord = tuple[int, ...]
TISpecifier = tuple[Coord, int]  # (coordinate tuple, internal generator number)


def _standardize_ti_locs(listlist, dim: int, dimension: int) -> list[set[TISpecifier]]:
    """Validate a list of TI locations and bring it into standard form:
    each location a set of pairs (coordinate tuple, internal number)."""
    standardized = []
    for mlist in listlist:
        specifiers = set()
        for coord, intern in mlist:
            coord = tuple(coord)
            if len(coord) != dimension:
                raise ValueError(f"Coordinate {coord} has wrong number of entries (should be {dimension})")
            if intern < 0 or intern >= dim:
                raise ValueError(f"Internal number {intern} given but must be between 0<={intern}<{dim}")
            specifiers.add((coord, intern))
        standardized.append(specifiers)
    return standardized


def normalize_ti_loc(loc: Iterable[TISpecifier]) -> tuple[Coord, set[TISpecifier]]:
    """Split a translation-invariant location into a shift and a normalized location.

    The normalized location is shifted such that its "smallest" specifier sits at
    coordinate 0, where specifiers are compared first by coordinate (lexicographically)
    and then by internal number. Returns the pair (shift, normalized location), such
    that the input is the normalized location translated by the shift.
    """
    coordmin, _ = min(loc)
    normalized = {(tuple(a - b for a, b in zip(coord, coordmin)), intern) for coord, intern in loc}
    return coordmin, normalized


class TIPhaseLocs:
    """Supports of translation classes of phase function generators.

    Each generator of level l represents a translation-invariant phase function:
    the phase function with support locs[l][i] applied at every lattice translate.
    Supports are always stored normalized and consolidated (add_loc normalizes and
    keeps each support only at its highest level).

    Attributes:
        dim: number of module generators (qubits) per unit cell
        dimension: number of spatial dimensions
        locs: locs[l][i] is the normalized support of the i-th generator of level l,
            a frozenset of (coordinate tuple, internal number) pairs
    """

    def __init__(self, dim: int, dimension: int,
                 locs: Optional[Sequence[Sequence[Iterable[TISpecifier]]]] = None):
        self.dim = dim
        self.dimension = dimension
        self.locs: list[list[frozenset[TISpecifier]]] = []
        if locs is not None:
            for l, llocs in enumerate(locs):
                self.add_locs(llocs, l)

    @property
    def dims(self) -> list[int]:
        """Number of generators per level."""
        return [len(llocs) for llocs in self.locs]

    def extend_levels(self, l: int) -> None:
        """Reserve space for generators of levels up to l."""
        if len(self.locs) <= l:
            self.locs += [[] for _ in range(l - len(self.locs) + 1)]

    def add_loc(self, loc: Iterable[TISpecifier], l: int) -> None:
        """Add a single generator support at level l, validating, normalizing and consolidating.

        The support is normalized (see normalize_ti_loc). Does nothing if the normalized
        support already occurs at level l or higher; if it occurs at a lower level it is
        moved up to l (a support is kept only at its highest level).
        """
        (standardized,) = _standardize_ti_locs([loc], self.dim, self.dimension)
        norm = frozenset(normalize_ti_loc(standardized)[1])
        self.extend_levels(l)
        if any(norm in self.locs[higher] for higher in range(l, len(self.locs))):
            return
        for lower in range(l):
            if norm in self.locs[lower]:
                self.locs[lower].remove(norm)
        self.locs[l].append(norm)

    def add_locs(self, locs: Iterable[Iterable[TISpecifier]], l: int) -> None:
        """Add generator supports at level l, validating and normalizing them (see add_loc)."""
        for loc in locs:
            self.add_loc(loc, l)

    def add_all_single_qubit_gates(self, l: int) -> None:
        """Add all singleton supports {((0,...,0), intern)} at level l (single-qubit ansatz gates of order 2^(l+1))."""
        self.add_locs([{((0,) * self.dimension, intern)} for intern in range(self.dim)], l)

    def add_gates_in_groups(self, groups, l: int, k: int) -> None:
        """Add all k-subset supports at level l within each group in "groups".

        Each group is a collection of (coord tuple, internal number) pairs; groups may
        also be given as a TIZ2Hom (e.g. a TIGateFinder's checks). Supports are normalized.
        """
        if isinstance(groups, TIZ2Hom):
            groups = groups.h
        for group in _standardize_ti_locs(groups, self.dim, self.dimension):
            self.add_locs(combinations(group, k), l)

    def add_gates_in_coord_group(self, group, l: int, k: int) -> None:
        """Add all k-subset supports at level l among the qubits supported on the given set of coordinates."""
        qubits = [(tuple(coord), intern) for coord in group for intern in range(self.dim)]
        self.add_locs(combinations(qubits, k), l)

    def compactify(self, compactification_data) -> tuple[PhaseLocs, "TwoGroupHom"]:
        """Compactify onto a finite lattice.

        Returns the pair (finite PhaseLocs, induced homomorphism). Every generator support is
        repeated once per unit cell and its (coord, internal) specifiers are mapped to global
        qubit numbers (see extract_compactification_data); coincident specifiers collapse
        idempotently (PhaseLocs.add_loc).

        The induced homomorphism is a TwoGroupHom from this (translation-invariant) phase group
        to the finite one (phase_locs1 = self, phase_locs0 = the finite locs). It sends each TI
        generator to the sum over all unit cells of the finite generator that its translate lands
        on. Composing it with a TwoGroupHom whose target is this TI phase group transports that hom
        to the finite code; e.g. TIGateFinder.as_finite_code obtains the finite transphys_allphys
        by composing it with the TI transphys_allphys.
        """
        total_dim = compactification_data[2]
        result = PhaseLocs(total_dim * self.dim)
        for l, llocs in enumerate(self.locs):
            result.add_locs(generate_ti_list(compactification_data, llocs), l)

        loc_index = {loc: (flev, i) for flev, llocs in enumerate(result.locs) for i, loc in enumerate(llocs)}
        h = lin.Hom.zeros(result.dims, self.dims)
        for l in range(len(self.locs)):
            for i in range(total_dim):
                shift = nr_to_coord(i, compactification_data)
                for g in range(len(self.locs[l])):
                    loc = frozenset(compactify_ti_specifier(compactification_data, (coord + shift, intern))
                                    for coord, intern in self.locs[l][g])
                    flev, idx = loc_index[loc]
                    h[flev, l][idx, g] += 1
        h.reduce_mod()
        return result, TwoGroupHom(h, phase_locs0=result, phase_locs1=self)


class TIZ2Hom:
    """Translation-invariant Z2-linear map between infinite Z2 modules, in sparse column form.

    Column j lists the images (coordinate, internal number) of the source generator
    (0, j) at the origin; by translation invariance the generator (c, j) maps to the
    same set of specifiers shifted by c. In QEC terms this stores e.g. the check map
    of a TI code: columns = checks per unit cell, rows = qubits per unit cell.

    Attributes:
        h: h[j] is the list of (coordinate tuple, internal number) pairs of column j
        dim0: target dimension per unit cell (range of the internal numbers in h)
        dim1: source dimension per unit cell (number of columns, equal to len(h))
        dimension: number of spatial dimensions
    """

    def __init__(self, dim0: int, dimension: int,
                 columns: Optional[Iterable[Iterable[TISpecifier]]] = None):
        self.dim0 = dim0
        self.dimension = dimension
        self.h: list[list[TISpecifier]] = []
        if columns is not None:
            self.add_columns(columns)

    @property
    def dim1(self) -> int:
        return len(self.h)

    def add_columns(self, columns: Iterable[Iterable[TISpecifier]]) -> None:
        if isinstance(columns, TIZ2Hom):
            columns = columns.h
        for col in _standardize_ti_locs(columns, self.dim0, self.dimension):
            self.h.append(sorted(col))

    def transpose(self) -> "TIZ2Hom":
        """Transpose of the translation-invariant Z2-linear map.

        Since (0, j) -> (coord, i) means the (infinite) coefficient matrix has
        M[(coord, i), (0, j)] = 1, the transpose has (0, i) -> (-coord, j).
        """
        transposed: list[list[TISpecifier]] = [[] for _ in range(self.dim0)]
        for j, col in enumerate(self.h):
            for coord, i in col:
                transposed[i].append((tuple(-c for c in coord), j))
        return TIZ2Hom(self.dim1, self.dimension, transposed)

    def __matmul__(self, other: "TIZ2Hom") -> "TIZ2Hom":
        if not isinstance(other, TIZ2Hom):
            return NotImplemented
        if other.dim0 != self.dim1:
            raise ValueError("Dimension mismatch in TIZ2Hom composition")
        columns = []
        for col in other.h:
            parity: dict[TISpecifier, int] = {}
            for coord, k in col:
                for coord2, i in self.h[k]:
                    key = (tuple(a + b for a, b in zip(coord, coord2)), i)
                    parity[key] = parity.get(key, 0) ^ 1
            columns.append([key for key, p in parity.items() if p])
        return TIZ2Hom(self.dim0, self.dimension, columns)

    def is_zero(self) -> bool:
        return all(len(col) == 0 for col in self.h)

    def compactify(self, compactification_data) -> Z2Hom:
        """Compactify onto a finite lattice, returning a plain (finite) Z2Hom.

        Every column is repeated once per unit cell and its (coord, internal) specifiers are
        mapped to global qubit numbers (see extract_compactification_data). Coincident
        specifiers cancel in Z2 (handled by Z2Hom.add_columns).
        """
        total_dim = compactification_data[2]
        result = Z2Hom(total_dim * self.dim0)
        result.add_columns(generate_ti_list(compactification_data, self.h))
        return result

    def phase_pullback(self, phase_locs: TIPhaseLocs) -> "TITwoGroupHom":
        """Pull back translation-invariant phase functions along this Z2-linear map.

        Each source generator of the result is a translation class of phase functions
        on the target module of self (an ansatz gate applied at all translates of its
        location). Its pullback is a phase function on the source module of self (the
        checks), supported on combinations of specifiers with both coordinate and
        internal number. The combinations are normalized, and the shift is recorded in
        the ti_support attribute of the returned TITwoGroupHom, whose phase_locs0
        holds the normalized combinations.

        Summing the result over all translates (TITwoGroupHom.ti_sum) yields the
        homomorphism whose kernel corresponds to the translation-invariant
        transversal gates.
        """
        if phase_locs.dim != self.dim0 or phase_locs.dimension != self.dimension:
            raise ValueError("phase_locs must live on the target module of self")
        # for each internal target number, the columns of self containing it (with relative shift)
        reverse = self.transpose().h

        columns = []
        for l, llocs in enumerate(phase_locs.locs):
            lcols = []
            for loc in llocs:
                # the columns acting on (qcoord, intern) are the columns acting on (0, intern), shifted by qcoord
                check_lists = [[(tuple(qc + cc for qc, cc in zip(qcoord, ccoord)), j) for ccoord, j in reverse[intern]]
                               for qcoord, intern in loc]
                column = pullback_column(check_lists, l)
                # label each target combination by its shift and normalized form
                keyed = {}
                for combo, val in column.items():
                    shift, normalized = normalize_ti_loc(combo)
                    keyed[(shift, frozenset(normalized))] = val
                lcols.append(keyed)
            columns.append(lcols)

        # all translates of the same normalized combination must share one 2-group
        # level, so that ti_sum can later sum them within each level
        h, target_keys = assemble_pullback(columns, phase_locs.dims, level_key=lambda key: key[1])

        target_locs = TIPhaseLocs(self.dim1, self.dimension)
        ti_support: list[list[TISpecifier]] = []
        for lev, lkeys in enumerate(target_keys):
            target_locs.extend_levels(lev)
            class_indices: dict = {}
            support_lev = []
            for shift, cls in lkeys:
                if cls not in class_indices:
                    class_indices[cls] = len(target_locs.locs[lev])
                    target_locs.locs[lev].append(cls)
                support_lev.append((shift, class_indices[cls]))
            ti_support.append(support_lev)

        return TITwoGroupHom(h, ti_support, phase_locs0=target_locs, phase_locs1=phase_locs)


class TITwoGroupHom:
    """Homomorphism into a 2-group generated by lattice translates of internal generators.

    The source 2-group is either a group of translation classes (like the generators
    of a TIPhaseLocs) or an abstract finite 2-group. The target 2-group is generated
    by translates of internal generators; since only finitely many appear, their
    specifiers are stored in ti_support while h stores the block coefficients.

    Attributes:
        h: lin.Hom object holding the block coefficient matrix
        ti_support: ti_support[l][r] is the (coordinate tuple, internal number) pair
            identifying the r-th target generator of level l, so
            len(ti_support[l]) == h.dim0[l]. The internal numbers index
            phase_locs0.locs[l] if phase_locs0 is given.
        phase_locs0: TIPhaseLocs describing the supports of the internal target
            generators, or None
        phase_locs1: TIPhaseLocs describing the supports of the source generators,
            or None if the source is an abstract 2-group
    """

    def __init__(self, h: lin.Hom, ti_support: Sequence[Sequence[TISpecifier]],
                 phase_locs0: Optional[TIPhaseLocs] = None,
                 phase_locs1: Optional[TIPhaseLocs] = None):
        if len(ti_support) != len(h.dim0) or any(len(s) != d for s, d in zip(ti_support, h.dim0)):
            raise ValueError("ti_support must have one specifier per target generator of h")
        if phase_locs1 is not None:
            _check_phase_locs_dims(phase_locs1, h.dim1, "phase_locs1")
        if phase_locs0 is not None:
            # each target generator refers, via ti_support, to an internal generator of phase_locs0
            pdims = phase_locs0.dims
            for l, support in enumerate(ti_support):
                for _, g in support:
                    if not 0 <= g < (pdims[l] if l < len(pdims) else 0):
                        raise ValueError(f"ti_support level {l} refers to internal generator {g} absent from phase_locs0")
        self.h = h
        self.ti_support = [list(s) for s in ti_support]
        self.phase_locs0 = phase_locs0
        self.phase_locs1 = phase_locs1

    @property
    def dim0(self) -> list[int]:
        return self.h.dim0

    @property
    def dim1(self) -> list[int]:
        return self.h.dim1

    def __matmul__(self, other: Union["TITwoGroupHom", TwoGroupElem, "TITwoGroupElem", lin.Elem]):
        """Composition with another TITwoGroupHom, or application to a (TI)(TwoGroup)Elem.

        The target generators of other are translates (given by other.ti_support, or by
        the standard generators for a plain element) of the source generators of self; by
        translation covariance, self maps such a translate to the correspondingly shifted
        column of self. Result generators landing on the same translate are merged. As for
        TwoGroupHom, composition/application requires the shared phase_locs to be the same
        object (checked with "is"); a raw lin.Elem carries no phase_locs and is accepted.
        """
        if isinstance(other, (lin.Elem, TwoGroupElem, TITwoGroupElem)):
            e = other if isinstance(other, lin.Elem) else other.e
            pl = None if isinstance(other, lin.Elem) else other.phase_locs
            if pl is not None and pl is not self.phase_locs1:
                raise ValueError("Application requires elem.phase_locs is self.phase_locs1")
            return TITwoGroupElem(self.h @ e, self.ti_support, phase_locs=self.phase_locs0)
        if not isinstance(other, TITwoGroupHom):
            return NotImplemented
        if other.phase_locs0 is not self.phase_locs1:
            raise ValueError("Composition requires other.phase_locs0 is self.phase_locs1")
        if len(other.h.dim0) > len(self.h.dim1):
            raise ValueError("Target of other exceeds the levels of the source of self")

        # collect the merged target support and the entries of the map sending each
        # target generator of other to the shifted column of self
        n_lev = len(self.h.dim0)
        indices: list[dict[TISpecifier, int]] = [{} for _ in range(n_lev)]
        merged_support: list[list[TISpecifier]] = [[] for _ in range(n_lev)]
        entries = []  # (target level, target index, source level, source index, coefficient)
        for lB in range(len(other.h.dim0)):
            for k, (shift, g) in enumerate(other.ti_support[lB]):
                if g >= self.h.dim1[lB]:
                    raise ValueError("ti_support of other refers to a non-existing source generator of self")
                for li in range(n_lev):
                    block = self.h[li, lB]
                    for r in range(self.h.dim0[li]):
                        c = block[r, g]
                        if c == 0:
                            continue
                        coord, intern = self.ti_support[li][r]
                        key = (tuple(a + b for a, b in zip(coord, shift)), intern)
                        if key not in indices[li]:
                            indices[li][key] = len(merged_support[li])
                            merged_support[li].append(key)
                        entries.append((li, indices[li][key], lB, k, c))

        shifted = lin.Hom.zeros([len(s) for s in merged_support], other.h.dim0)
        for li, row, lB, k, c in entries:
            shifted[li, lB][row, k] += c
        shifted.reduce_mod()

        return TITwoGroupHom(shifted @ other.h, merged_support,
                             phase_locs0=self.phase_locs0, phase_locs1=other.phase_locs1)

    def ti_sum(self) -> TwoGroupHom:
        """Sum the target over all lattice translates.

        Target generators that are translates of the same internal generator are summed
        into that internal generator, forgetting the coordinates. The result is a
        TwoGroupHom into the 2-group of translation classes described by phase_locs0
        (which is passed on unchanged, as is phase_locs1).
        """
        n_lev = len(self.h.dim0)
        if self.phase_locs0 is not None:
            target_dims = self.phase_locs0.dims
            if len(target_dims) < n_lev:
                raise ValueError("phase_locs0 has fewer levels than the target of h")
        else:
            target_dims = [1 + max((g for _, g in self.ti_support[l]), default=-1) for l in range(n_lev)]

        summed = lin.Hom.zeros(target_dims, self.h.dim1)
        for li in range(n_lev):
            for r, (_, g) in enumerate(self.ti_support[li]):
                summed[li, :][g, :] += self.h[li, :][r, :]
        summed.reduce_mod()
        return TwoGroupHom(summed, phase_locs0=self.phase_locs0, phase_locs1=self.phase_locs1)

    def kernel(self, return_solve_helper: bool = False):
        """Kernel as a TwoGroupHom into the source 2-group of self (phase_locs0 = self.phase_locs1)."""
        if return_solve_helper:
            k, helper = self.h.kernel(return_solve_helper=True)
            return TwoGroupHom(k, phase_locs0=self.phase_locs1), helper
        return TwoGroupHom(self.h.kernel(), phase_locs0=self.phase_locs1)

    def to_string(self) -> str:
        """Write the images of all source generators as a string, one line per generator.

        Target generators are labeled by their (coordinate, internal number) pair if
        phase_locs0 is None, else by their phase_locs0 support shifted by the coordinate.
        """
        out = ""
        for lj in range(len(self.h.dim1)):
            out += f"order {2 ** (lj + 1)}\n"
            for j in range(self.h.dim1[lj]):
                terms = []
                for li in range(len(self.h.dim0)):
                    for i in range(self.h.dim0[li]):
                        c = self.h[li, lj][i, j]
                        if c != 0:
                            shift, g = self.ti_support[li][i]
                            if self.phase_locs0 is None:
                                label = (shift, g)
                            else:
                                label = sorted({(tuple(a + b for a, b in zip(coord, shift)), intern)
                                                for coord, intern in self.phase_locs0.locs[li][g]})
                            terms.append(f"{c}/{2 ** (min(li, lj) + 1)}*{label}")
                out += ", ".join(terms) + "\n"
        return out


class TITwoGroupElem:
    """Element of a 2-group generated by lattice translates of internal generators.

    Attributes:
        e: lin.Elem holding the coefficient vector
        ti_support: ti_support[l][r] = (coord, internal number) identifying the r-th
            generator of level l as a translate; len(ti_support[l]) == e.dim[l]
        phase_locs: TIPhaseLocs describing the internal generator supports, or None
    """

    def __init__(self, e: lin.Elem, ti_support: Sequence[Sequence[TISpecifier]],
                 phase_locs: Optional[TIPhaseLocs] = None):
        if len(ti_support) != len(e.dim) or any(len(s) != d for s, d in zip(ti_support, e.dim)):
            raise ValueError("ti_support must have one specifier per generator of e")
        self.e = e
        self.ti_support = [list(s) for s in ti_support]
        self.phase_locs = phase_locs

    @property
    def dim(self) -> list[int]:
        return self.e.dim

    @property
    def v(self) -> np.ndarray:
        return self.e.v

    def to_string(self) -> str:
        """Write the element as a string; generators labeled by their (coord, internal number)
        pair if phase_locs is None, else by their phase_locs support shifted by the coordinate."""
        terms = []
        for li in range(len(self.e.dim)):
            for i in range(self.e.dim[li]):
                c = self.e[li][i]
                if c != 0:
                    shift, g = self.ti_support[li][i]
                    if self.phase_locs is None:
                        label = (shift, g)
                    else:
                        label = sorted({(tuple(a + b for a, b in zip(coord, shift)), intern)
                                        for coord, intern in self.phase_locs.locs[li][g]})
                    terms.append(f"{c}/{2 ** (li + 1)}*{label}")
        return ", ".join(terms)


def extract_compactification_data(lattice):
    """Compute the compactification data for putting a TI code on a finite lattice.

    Parameters:
        lattice: Matrix whose *rows* are the boundary vectors identified with the origin.

    Returns:
        The tuple (lattice_hnf, cum_dims, total_dim, periods), where lattice_hnf is the
        (row-operation) Hermite normal form of the lattice, periods its diagonal (the
        number of cells along each axis), total_dim the number of unit cells, and cum_dims
        the cumulative cell strides used to index cells. This tuple is passed around as
        "compactification_data" by TIZ2Hom.compactify, TIPhaseLocs.compactify and the
        coordinate helpers of TIGateFinder.
    """
    lattice = np.asarray(lattice, dtype=int)
    lattice_hnf = fl.hnf(lattice)[0]  # row-operation hnf
    periods = lattice_hnf.diagonal()
    total_dim = int(np.prod(periods))
    cum_dims = np.insert(np.cumprod(periods), 0, 1)[:-1]
    return lattice_hnf, cum_dims, total_dim, periods


def compactify_ti_specifier(compactification_data, specifier: TISpecifier) -> int:
    """Map a translation-invariant (coord, internal number) specifier to a global qubit number.

    The coordinate is reduced modulo the boundary lattice; the internal numbers of a cell are
    laid out contiguously across all cells. See extract_compactification_data for the meaning
    of compactification_data.
    """
    lattice_hnf, cum_dims, total_dim, _ = compactification_data
    coord, internal = specifier
    coord = np.array(coord)
    for d in range(len(coord)):
        offs = coord[d] // lattice_hnf[d, d]
        coord = coord - offs * lattice_hnf[d, :]
    return int(np.dot(coord, cum_dims) + internal * total_dim)


def nr_to_coord(nr, compactification_data) -> np.ndarray:
    """Convert a cell index (0 <= nr < total_dim) into its unit-cell coordinate vector. This is just for conveniently iterating over all coordinates without tools like itertools.product"""
    _, cum_dims, _, periods = compactification_data
    return np.array(nr)[None] // cum_dims % periods


def generate_ti_list(compactification_data, qubit_listlist):
    """Repeat each TI location once per unit cell, mapping the specifiers to global qubit numbers."""
    total_dim = compactification_data[2]
    output_listlist = []
    for i in range(total_dim):
        shift_coord = nr_to_coord(i, compactification_data)
        for qubit_list in qubit_listlist:
            output_listlist.append([compactify_ti_specifier(compactification_data, (coord + shift_coord, intern))
                                    for coord, intern in qubit_list])
    return output_listlist


class TIGateFinder:
    """Helper class for analyzing translation-invariant codes in n dimensions.

    Attributes:
        dimension: spatial dimension of translation-invariant CSS code
        nr_qubits: number of qubits *per unit cell*
        checks: X checks as a TIZ2Hom (columns = checks per unit cell, rows = qubits per unit cell)
        other_checks: Z checks (optional) as a TIZ2Hom
        gates: Ansatz gates as a TIPhaseLocs object; each generator is one gate applied
            at all lattice translates of its location
        local_gates: Locally supported (non-translation-invariant) gate configurations,
            used by find_gates_nonlocal. A TITwoGroupHom from an abstract finite 2-group
            to the group of translates of the ansatz gates (phase_locs0 = self.gates);
            set it via set_local_gates. None before set_local_gates is called.

    find_gates_nonlocal() and find_gates_compactify() each return a GateFinderResults
    (see that class). Its transphys_allphys is always the TI map from the
    abstract group T of translation-invariant transversal gates to the group G of all TI
    physical ansatz gate configurations (phase_locs0 = self.gates), so find_phys_rep returns
    representatives as translation-invariant ansatz-gate coefficients (one per unit cell).
    """
    def __init__(self, nr_qubits: int, dimension: int, checks=None, gates=None, other_checks=None):
        self.nr_qubits = nr_qubits
        self.dimension = dimension
        self.checks = TIZ2Hom(nr_qubits, dimension, checks)
        self.other_checks = TIZ2Hom(nr_qubits, dimension, other_checks)
        self.gates = TIPhaseLocs(nr_qubits, dimension, gates)
        self.local_gates: Optional[TITwoGroupHom] = None

    def standardize_locs(self, listlist) -> list[set[TISpecifier]]:
        """Validate a list of checks/gates and bring it into standard form:
        each check/gate a set of pairs (coordinate tuple, internal qubit number)."""
        return _standardize_ti_locs(listlist, self.nr_qubits, self.dimension)

    def print_gates(self) -> None:
        for l, lgates in enumerate(self.gates.locs):
            print(f"\nLevel {l}")
            for gate in lgates:
                print(set(gate))

    def set_local_gates(self, active_gates: Sequence[Sequence[tuple[Coord, int]]]) -> None:
        """Set self.local_gates from a list of active gate locations.

        Parameters:
            active_gates: active_gates[l] is a list of pairs of a shift coordinate
                (int tuple) and an internal gate number indexing self.gates.locs[l].
                Each entry is one independent local degree of freedom: the ansatz gate
                self.gates.locs[l][i], applied at the prescribed translate only.

        Sets self.local_gates to the corresponding canonical inclusion: a TITwoGroupHom
        from the free 2-group over the active locations to the group of translates of
        the ansatz gates.
        """
        support: list[list[TISpecifier]] = []
        for l in range(len(self.gates.locs)):
            lactive = active_gates[l] if l < len(active_gates) else []
            for shift, gate_nr in lactive:
                if not 0 <= gate_nr < len(self.gates.locs[l]):
                    raise ValueError(f"Gate number {gate_nr} out of range at level {l}")
            support.append([(tuple(shift), gate_nr) for shift, gate_nr in lactive])
        h = lin.Hom.identity([len(s) for s in support])
        self.local_gates = TITwoGroupHom(h, support, phase_locs0=self.gates)

    def compactify(self, lattice, auto_logicals: bool = True, ti_logicals=None,
                       manual_logicals=None, manual_gates=None) -> GateFinder:
        """Transform into a regular code by putting it on a finite lattice with twisted boundary conditions.

        Arguments:
            lattice: Matrix describing twisted periodic boundary conditions, used to construct a finite code from the unit-cell data. Numpy array whose *rows* are the vectors that are identified with the origin.
            auto_logicals: If True (default), set the logicals of the finite code from self.other_checks via GateFinder.logicals_from_other_checks().
            ti_logicals: Optional list of X logicals in translation-invariant format (like the columns of self.checks), which are transformed into finite-code logicals like the checks and gates, i.e. repeated once for every unit cell.
            manual_logicals: Optional list of X logicals given in (coord, internal) format; in contrast to ti_logicals these are not repeated for every unit cell, but provide a convenient way of defining individual finite-code logicals.
            manual_gates: Additional ansatz gates for the finite code, in the same format as self.gates.locs. In contrast to self.gates, they are not repeated for every unit cell; the (coord, internal) qubit specifiers just provide a convenient way of defining individual finite-code gate locations.
        """
        compactification_data = extract_compactification_data(lattice)
        total_dim = compactification_data[2]

        tgf = GateFinder(total_dim * self.nr_qubits)
        tgf.checks = self.checks.compactify(compactification_data)
        tgf.gates, _ = self.gates.compactify(compactification_data)
        # manual gates: extra finite ansatz gates, not repeated per unit cell
        if manual_gates is not None:
            for l, lgates in enumerate(manual_gates):
                tgf.gates.add_locs([[compactify_ti_specifier(compactification_data, spec) for spec in loc] for loc in lgates], l)
        tgf.other_checks = self.other_checks.compactify(compactification_data)

        # logicals derived from the Z checks (if requested); must come first since it overwrites tgf.logicals
        if auto_logicals:
            tgf.logicals_from_other_checks()
        # translation-invariant logicals: one copy for every unit cell (like the checks)
        if ti_logicals is not None:
            tgf.logicals.add_columns(TIZ2Hom(self.nr_qubits, self.dimension, ti_logicals).compactify(compactification_data))
        # manual logicals: finite-code specifiers, not repeated per unit cell
        if manual_logicals is not None:
            tgf.logicals.add_columns([[compactify_ti_specifier(compactification_data, spec) for spec in loc] for loc in manual_logicals])

        return tgf

    def _find_transversal(self) -> tuple[TwoGroupHom, object]:
        """Compute the space of all translation-invariant transversal gates.

        Internal helper feeding find_gates_nonlocal and find_gates_compactify. Returns the pair
        (transphys_allphys, transphys_solve_helper), where transphys_allphys is a TwoGroupHom from
        the abstract 2-group of translation-invariant transversal gates to the group of
        configurations of all physical ansatz gates, and transphys_solve_helper is its kernel
        solve helper.
        """
        allphys_allcheck = self.checks.phase_pullback(self.gates).ti_sum()
        transphys_allphys = allphys_allcheck.kernel()
        _, transphys_solve_helper = transphys_allphys.kernel(return_solve_helper = True)
        return transphys_allphys, transphys_solve_helper

    def find_gates_nonlocal(self) -> GateFinderResults:
        """Compute the translation-invariant transversal gates modulo sums of translates of local transversal gates.

        First calls _find_transversal() to get the group T of translation-invariant transversal
        gates. Then computes the group of locally supported transversal gates on the
        active locations self.local_gates (see set_local_gates) as the kernel of the
        pullback composed with the local gate inclusion. Summing such a local gate
        configuration over all lattice translates yields a translation-invariant
        configuration (the shift of each active gate is forgotten, which is
        self.local_gates.ti_sum()); these are quotiented out of T.

        Returns a GateFinderResults with transphys_translog set: a surjective TwoGroupHom from
        T to the quotient 2-group N. Elements of N are classes of TI transversal gates that
        differ by sums of translates of local transversal gates; nontrivial classes cannot be
        generated locally. Also sets rep_find_helper (kernel solve helper for T -> N), so
        find_phys_rep can return physical representatives, and keeps transphys_allphys (the TI
        map T -> G).
        """
        transphys_allphys, transphys_solve_helper = self._find_transversal()
        if self.local_gates is None:
            raise ValueError("Call set_local_gates before find_gates_nonlocal")
        local_pullback = self.checks.phase_pullback(self.gates) @ self.local_gates
        local_transversal = local_pullback.kernel()
        # sum over all translates: each active local gate (shift, gate_nr) contributes to the TI gate gate_nr
        translate_sum = self.local_gates.ti_sum()
        quotient = transphys_allphys.h.quotient_image_by_image(
            (translate_sum @ local_transversal).h, transphys_solve_helper)
        transphys_translog = TwoGroupHom(quotient)
        _, rep_find_helper = transphys_translog.kernel(return_solve_helper = True)
        return GateFinderResults(
            transphys_allphys=transphys_allphys,
            transphys_translog=transphys_translog,
            rep_find_helper=rep_find_helper,
            transphys_solve_helper=transphys_solve_helper,
        )

    def find_gates_compactify(self, lattice, auto_logicals: bool = True, manual_logicals=None) -> GateFinderResults:
        """Find transversal gates that are non-trivial after compactification onto a finite lattice.

        Here "non-trivial" means acting non-trivially as a logical gate on the compactified
        finite code (contrast find_gates_nonlocal, where non-trivial means "not a translation-
        invariant sum of local terms"). Computes the translation-invariant transversal gates
        (_find_transversal), builds the compactified finite code (as_finite_code) and transports
        the transversal gates onto it via the induced compactification homomorphism, then runs the
        finite code's logical-action analysis.

        Returns a GateFinderResults whose transphys_allphys stays the translation-invariant map
        T -> G, with the logical-action maps (translog_alllog, transphys_translog,
        log_find_helper, rep_find_helper) taken from the compactified finite code and stabphys_allphys
        rebuilt against the TI map. Because transphys_allphys stays the TI map, find_phys_rep returns
        representatives as coefficients on the *translation-invariant* ansatz gates (one per unit
        cell), not on the finite gates.
        """
        transphys_allphys, _ = self._find_transversal()
        compactification_data = extract_compactification_data(lattice)
        tgf = self.compactify(lattice, auto_logicals=auto_logicals, manual_logicals=manual_logicals)
        # recompactify the gates to obtain the induced hom whose target *is* tgf.gates, then transport
        # the TI transversal gates onto the finite code and analyse their logical action there.
        tgf.gates, gates_compactify = self.gates.compactify(compactification_data)
        finite_results = tgf.find_logical_action(gates_compactify @ transphys_allphys)
        # keep transphys_allphys as the TI map T -> G so find_phys_rep expresses representatives as
        # translation-invariant ansatz-gate coefficients; rebuild stabphys_allphys against that map
        stabphys_transphys = finite_results.transphys_translog.kernel()  # trivial-logical-action transversal gates
        return GateFinderResults(
            transphys_allphys=transphys_allphys,
            transphys_translog=finite_results.transphys_translog,
            translog_alllog=finite_results.translog_alllog,
            log_find_helper=finite_results._log_find_helper,
            rep_find_helper=finite_results._rep_find_helper,
            stabphys_allphys=transphys_allphys @ stabphys_transphys,
        )

    def __add__(self, other: "TIGateFinder") -> "TIGateFinder":
        if self.dimension != other.dimension:
            raise ValueError("Space(time) dimensions of added codes must agree.")
        res = TIGateFinder(self.nr_qubits + other.nr_qubits, self.dimension)
        for attr in ("checks", "other_checks"):
            getattr(res, attr).add_columns(getattr(self, attr).h)
            getattr(res, attr).add_columns(shift_ti_loc_list(getattr(other, attr).h, self.nr_qubits))
        for l, llocs in enumerate(self.gates.locs):
            res.gates.add_locs(llocs, l)
        for l, llocs in enumerate(other.gates.locs):
            res.gates.add_locs(shift_ti_loc_list(llocs, self.nr_qubits), l)
        return res

    def inverted_coordinates(self) -> "TIGateFinder":
        """
        Invert all spatial coordinates
        """
        def invert_coords(mlist):
            return [{(tuple(-c for c in coord), i) for coord, i in entry} for entry in mlist]
        return TIGateFinder(self.nr_qubits,
                            self.dimension,
                            checks = invert_coords(self.checks.h),
                            other_checks = invert_coords(self.other_checks.h),
                            gates = [invert_coords(lgates) for lgates in self.gates.locs])


def shift_ti_loc_list(loc_list, shift: int) -> list[set[TISpecifier]]:
    """Shift the internal qubit number (needed for addition of codes)."""
    return [{(coord, intern+shift) for coord, intern in loc} for loc in loc_list]


def twobga_code(dimension: int, poly1, poly2) -> TIGateFinder:
    """Creates an "infinite" abelian 2-block group-algebra code from two polynomials. After compactification with as_finite_code() this is a true 2-block group-algebra code."""
    code = TIGateFinder(2, dimension)
    code.checks.add_columns([[(tuple(coord), 0) for coord in poly1] + [(tuple(coord), 1) for coord in poly2]])
    code.other_checks.add_columns([[(tuple(-c for c in coord), 1) for coord in poly1] + [(tuple(-c for c in coord), 0) for coord in poly2]])
    return code
